### ISSUE TITLE
Implement additional healthcheck types

### ISSUE THREAD

**Issue by zcahana** [amalgam8/amalgam8#314]
Currently we have support for HTTP-based health checks only. It can be useful to support several other types:
- TCP-based healthcheck - attempt to establish a TCP connection to a given `host:port`.
- Command-based healthcheck - invoke a given command (optionally with arguments) and examine exit status.

Example configuration:

``` yaml
healthchecks:
  - type: tcp
    value: localhost:5053
    interval: 30s
    timeout: 1s

  - type: command
    value: /opt/myapp/health.sh
    interval: 60s
    timeout: 3s

  - type: command
    value: /bin/grep
    args: [ "-i", "ERROR", "/opt/myapp/out.log"]
    interval: 60s
    timeout: 3s
```

Note: it may be beneficial to refactor the healthcheck mechanism so that `HealthCheck` interface is responsible for a single execution of the healthcheck only (i.e., `Execute()` instead of `Start()` and `Stop()`).  This way we don't have to re-implement the scheduling logic in each of the healthcheck types. This also make it easier to test each of the healthcheck implementations.
