### ISSUE TITLE
Go CLI: Stdin input for rule-create should be terminated by EOF

### ISSUE THREAD

**Issue by frankbu** [amalgam8/amalgam8#412]
The `rule-create` command, without the -f option accepts input from stdin, however the current implementation requires the input to be terminated by typing `.yaml` or `.json` alone on a line. It works like this:
```
*** Write .json or .yaml in a new line when finished ***
Enter DSL Rules:

rules:
- id: yaml_id
  destination: yaml_destination
  route:
    backends:
      - name: service1
        tags: [ v11, v12 ]
      - name: service2
        tags: [ v21, v22, yaml ]
.yaml
```
This needs to be changed to allow the user to simply terminate the input in the expected standard way, by entering EOF, that is: ^Z (CtrlZ) in Windows, ^D on Unix-like systems.
