### ISSUE TITLE
k8s rules controller does not set status if marshalling fails

### ISSUE THREAD

**Issue by elevran** [amalgam8/amalgam8#498]
When defining a k8s TPR rule with the wrong schema, the unmarshal error is logged but not reflected in the rule's Status.
For example (version is specified in tags and isn't  an array): 
```yaml
apiVersion: "amalgam8.io/v1"
kind: RoutingRule
metadata:
  name: "set-helloworld-v1-default"
spec:
  destination: "helloworld"
  route:
    backends:
    -tags:"version=v1"
``` 
Will produce the following error

`E0206 12:26:40.861494       1 reflector.go:214] github.com/amalgam8/amalgam8/vendor/k8s.io/client-go/tools/cache/reflector.go:109: Failed to list *kubernetes.RoutingRule: json: cannot unmarshal object into Go value of type []api.Backend`

But will not set the rule's status to `Invalid`
@zachidan
