### ISSUE TITLE
k8srules controller overwrites id, destination and priority

### ISSUE THREAD

**Issue by elevran** [amalgam8/amalgam8#502]
Given the following rule definition:
```yaml
apiVersion: "amalgam8.io/v1"
kind: RoutingRule
metadata:
  name: "test-hw"
spec:
  priority: 1
  id: "test"
  destination: "helloworld"
  route:
    backends:
    - tags:
      - "version=v1"
```
When the status is set to `valid`, the `id`, `destination` and `priority` fields are nullified (i.e., set to empty strings and 0, respectively). This is most likely due to the interaction between the resource patching in the controller and not having `omitempty` set for these fields.
