### ISSUE TITLE
[CLOSED] Add support for configuration files (resolves #54)

### ISSUE THREAD

**Issue by a8bot** [amalgam8/amalgam8#60]
<a href="https://github.com/zcahana"><img src="https://avatars.githubusercontent.com/u/17428696?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zcahana](https://github.com/zcahana)**
_Thursday Sep 01, 2016 at 13:22 GMT_
_Originally opened as https://github.com/amalgam8/sidecar/pull/60_

---
- File is in YAML format
- Configuration is loaded from a file specified with `--config` cmdline flag (or A8_CONFIG env var)
- Configuration precendence is: flags --> env vars --> config file --> default values

---

_**[zcahana](https://github.com/zcahana)** included the following code: https://github.com/amalgam8/sidecar/pull/60/commits_

**Comment by a8bot** [comment]
<a href="https://github.com/zcahana"><img src="https://avatars.githubusercontent.com/u/17428696?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [zcahana](https://github.com/zcahana)**
_Thursday Sep 01, 2016 at 13:24 GMT_

---

Example configuration file:

``` yaml
register: true
proxy: true

service:
  name: helloworld
  tags: 
    - v1
    - somethingelse

endpoint:
  host: 172.10.10.1
  port: 9080
  type: https

registry:
  url:   http://registry:8080
  token: abcdef
  poll:  10s

controller:
  url:   http://controller:6379
  token: abcdef
  poll:  30s

supervise: true
app: [ "python", "helloworld.py ]

log: true
logstash_server: logstash:8092

log_level: debug
```
